#include <windows.h>
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

extern "C"
{
#include <lua.h>
#include <lauxlib.h>
#include <lualib.h>
}

#include "Constants.h"
#include "Lua.h"
#include "../cave_story.h"

typedef enum
{
	CONST_STATIC,
} ConstantType;

typedef struct
{
	const char* name;
	ConstantType type;

	int static_value;
	size_t limit_offset;
} CONSTANT_TABLE;

#define MODE_OPENING 1
#define MODE_TITLE 2
#define MODE_ACTION 3

#define CAVE_CONST(x) \
    { #x, CONST_STATIC, (x), 0 }

#define CAVE_CONST_NAMED(name, value) \
    { name, CONST_STATIC, (value), 0 }

static const CONSTANT_TABLE ConstantTable[] =
{
	// Max amounts
	CAVE_CONST(ARMS_MAX),
	CAVE_CONST(BOSS_MAX),
	CAVE_CONST(BULLET_MAX),
	CAVE_CONST(CARET_MAX),
	CAVE_CONST(ITEM_MAX),
	CAVE_CONST(MAX_STRIP),
	CAVE_CONST(NPC_MAX),
	CAVE_CONST(SE_MAX),
	CAVE_CONST(STAGE_MAX),
	CAVE_CONST(VALUEVIEW_MAX),

	// Game Modes
	CAVE_CONST(MODE_OPENING),
	CAVE_CONST(MODE_TITLE),
	CAVE_CONST(MODE_ACTION),

	// Background IDs
	CAVE_CONST(BACKGROUND_TYPE_STATIONARY),
	CAVE_CONST(BACKGROUND_TYPE_MOVE_DISTANT),
	CAVE_CONST(BACKGROUND_TYPE_MOVE_NEAR),
	CAVE_CONST(BACKGROUND_TYPE_WATER),
	CAVE_CONST(BACKGROUND_TYPE_BLACK),
	CAVE_CONST(BACKGROUND_TYPE_AUTOSCROLL),
	CAVE_CONST(BACKGROUND_TYPE_CLOUDS_WINDY),
	CAVE_CONST(BACKGROUND_TYPE_CLOUDS),

	// Caret IDs
	CAVE_CONST(CARET_NULL),
	CAVE_CONST(CARET_BUBBLE),
	CAVE_CONST(CARET_PROJECTILE_DISSIPATION),
	CAVE_CONST(CARET_SHOOT),
	CAVE_CONST(CARET_SNAKE_AFTERIMAGE),
	CAVE_CONST(CARET_ZZZ),
	CAVE_CONST(CARET_SNAKE_AFTERIMAGE_DUPLICATE),
	CAVE_CONST(CARET_EXHAUST),
	CAVE_CONST(CARET_DROWNED_QUOTE),
	CAVE_CONST(CARET_QUESTION_MARK),
	CAVE_CONST(CARET_LEVEL_UP),
	CAVE_CONST(CARET_HURT_PARTICLES),
	CAVE_CONST(CARET_EXPLOSION),
	CAVE_CONST(CARET_TINY_PARTICLES),
	CAVE_CONST(CARET_UNKNOWN),
	CAVE_CONST(CARET_PROJECTILE_DISSIPATION_TINY),
	CAVE_CONST(CARET_EMPTY),
	CAVE_CONST(CARET_PUSH_JUMP_KEY),

	// Credits Modes
	CAVE_CONST(CREDIT_MODE_STOP),
	CAVE_CONST(CREDIT_MODE_SCROLL_READ),
	CAVE_CONST(CREDIT_MODE_SCROLL_WAIT),

	// Direction IDs
	CAVE_CONST(DIR_LEFT),
	CAVE_CONST(DIR_UP),
	CAVE_CONST(DIR_RIGHT),
	CAVE_CONST(DIR_DOWN),
	CAVE_CONST(DIR_AUTO),
	CAVE_CONST(DIR_OTHER),

	// Player Equipment IDs
	CAVE_CONST(EQUIP_BOOSTER_0_8),
	CAVE_CONST(EQUIP_MAP),
	CAVE_CONST(EQUIP_ARMS_BARRIER),
	CAVE_CONST(EQUIP_TURBOCHARGE),
	CAVE_CONST(EQUIP_AIR_TANK),
	CAVE_CONST(EQUIP_BOOSTER_2_0),
	CAVE_CONST(EQUIP_MIMIGA_MASK),
	CAVE_CONST(EQUIP_WHIMSICAL_STAR),
	CAVE_CONST(EQUIP_NIKUMARU_COUNTER),

	CAVE_CONST_NAMED("ESCRETURN_exit", enum_ESCRETURN_exit),
	CAVE_CONST_NAMED("ESCRETURN_continue", enum_ESCRETURN_continue),
	CAVE_CONST_NAMED("ESCRETURN_restart", enum_ESCRETURN_restart),

	// Flash Modes
	CAVE_CONST(FLASH_MODE_EXPLOSION),
	CAVE_CONST(FLASH_MODE_FLASH),

	// Credits Illustrations
	CAVE_CONST(ILLUSTRATION_ACTION_IDLE),
	CAVE_CONST(ILLUSTRATION_ACTION_SLIDE_IN),
	CAVE_CONST(ILLUSTRATION_ACTION_SLIDE_OUT),

	// Key IDs
	CAVE_CONST(KEY_LEFT),
	CAVE_CONST(KEY_RIGHT),
	CAVE_CONST(KEY_UP),
	CAVE_CONST(KEY_DOWN),
	CAVE_CONST(KEY_MAP),
	CAVE_CONST(KEY_X),
	CAVE_CONST(KEY_Z),
	CAVE_CONST(KEY_ARMS),
	CAVE_CONST(KEY_ARMSREV),
	CAVE_CONST(KEY_SHIFT),
	CAVE_CONST(KEY_F1),
	CAVE_CONST(KEY_F2),
	CAVE_CONST(KEY_ITEM),
	CAVE_CONST(KEY_ESCAPE),

	CAVE_CONST(KEY_ALT_LEFT),
	CAVE_CONST(KEY_ALT_DOWN),
	CAVE_CONST(KEY_ALT_RIGHT),
	CAVE_CONST(KEY_ALT_UP),
	CAVE_CONST(KEY_L),
	CAVE_CONST(KEY_PLUS),

	// NPC Bit Flags
	CAVE_CONST(NPC_SOLID_SOFT),
	CAVE_CONST(NPC_IGNORE_TILE_44),
	CAVE_CONST(NPC_INVULNERABLE),
	CAVE_CONST(NPC_IGNORE_SOLIDITY),
	CAVE_CONST(NPC_BOUNCY),
	CAVE_CONST(NPC_SHOOTABLE),
	CAVE_CONST(NPC_SOLID_HARD),
	CAVE_CONST(NPC_REAR_AND_TOP_DONT_HURT),
	CAVE_CONST(NPC_EVENT_WHEN_TOUCHED),
	CAVE_CONST(NPC_EVENT_WHEN_KILLED),
	CAVE_CONST(NPC_APPEAR_WHEN_FLAG_SET),
	CAVE_CONST(NPC_SPAWN_IN_OTHER_DIRECTION),
	CAVE_CONST(NPC_INTERACTABLE),
	CAVE_CONST(NPC_HIDE_WHEN_FLAG_SET),
	CAVE_CONST(NPC_SHOW_DAMAGE),

	// Music IDs
	CAVE_CONST(MUS_SILENCE),
	CAVE_CONST(MUS_MISCHIEVOUS_ROBOT),
	CAVE_CONST(MUS_SAFETY),
	CAVE_CONST(MUS_GAME_OVER),
	CAVE_CONST(MUS_GRAVITY),
	CAVE_CONST(MUS_ON_TO_GRASSTOWN),
	CAVE_CONST(MUS_MELTDOWN2),
	CAVE_CONST(MUS_EYES_OF_FLAME),
	CAVE_CONST(MUS_GESTATION),
	CAVE_CONST(MUS_MIMIGA_TOWN),
	CAVE_CONST(MUS_GOT_ITEM),
	CAVE_CONST(MUS_BALROGS_THEME),
	CAVE_CONST(MUS_CEMETERY),
	CAVE_CONST(MUS_PLANT),
	CAVE_CONST(MUS_PULSE),
	CAVE_CONST(MUS_VICTORY),
	CAVE_CONST(MUS_GET_HEART_TANK),
	CAVE_CONST(MUS_TYRANT),
	CAVE_CONST(MUS_RUN),
	CAVE_CONST(MUS_JENKA1),
	CAVE_CONST(MUS_LABYRINTH_FIGHT),
	CAVE_CONST(MUS_ACCESS),
	CAVE_CONST(MUS_OPPRESSION),
	CAVE_CONST(MUS_GEOTHERMAL),
	CAVE_CONST(MUS_CAVE_STORY),
	CAVE_CONST(MUS_MOONSONG),
	CAVE_CONST(MUS_HEROS_END),
	CAVE_CONST(MUS_SCORCHING_BACK),
	CAVE_CONST(MUS_QUIET),
	CAVE_CONST(MUS_LAST_CAVE),
	CAVE_CONST(MUS_BALCONY),
	CAVE_CONST(MUS_CHARGE),
	CAVE_CONST(MUS_LAST_BATTLE),
	CAVE_CONST(MUS_THE_WAY_BACK_HOME),
	CAVE_CONST(MUS_ZOMBIE),
	CAVE_CONST(MUS_BREAK_DOWN),
	CAVE_CONST(MUS_RUNNING_HELL),
	CAVE_CONST(MUS_JENKA2),
	CAVE_CONST(MUS_LIVING_WATERWAY),
	CAVE_CONST(MUS_SEAL_CHAMBER),
	CAVE_CONST(MUS_TOROKOS_THEME),
	CAVE_CONST(MUS_WHITE),

	// Surface IDs
	CAVE_CONST(SURFACE_ID_TITLE),
	CAVE_CONST(SURFACE_ID_PIXEL),
	CAVE_CONST(SURFACE_ID_LEVEL_TILESET),
	CAVE_CONST(SURFACE_ID_FADE),
	CAVE_CONST(SURFACE_ID_ITEM_IMAGE),
	CAVE_CONST(SURFACE_ID_MAP),
	CAVE_CONST(SURFACE_ID_SCREEN_GRAB),
	CAVE_CONST(SURFACE_ID_ARMS),
	CAVE_CONST(SURFACE_ID_ARMS_IMAGE),
	CAVE_CONST(SURFACE_ID_ROOM_NAME),
	CAVE_CONST(SURFACE_ID_STAGE_ITEM),
	CAVE_CONST(SURFACE_ID_LOADING),
	CAVE_CONST(SURFACE_ID_MY_CHAR),
	CAVE_CONST(SURFACE_ID_BULLET),
	CAVE_CONST(SURFACE_ID_CARET),
	CAVE_CONST(SURFACE_ID_NPC_SYM),
	CAVE_CONST(SURFACE_ID_LEVEL_SPRITESET_1),
	CAVE_CONST(SURFACE_ID_LEVEL_SPRITESET_2),
	CAVE_CONST(SURFACE_ID_NPC_REGU),
	CAVE_CONST(SURFACE_ID_TEXT_BOX),
	CAVE_CONST(SURFACE_ID_FACE),
	CAVE_CONST(SURFACE_ID_LEVEL_BACKGROUND),
	CAVE_CONST(SURFACE_ID_VALUE_VIEW),
	CAVE_CONST(SURFACE_ID_TEXT_LINE1),
	CAVE_CONST(SURFACE_ID_TEXT_LINE2),
	CAVE_CONST(SURFACE_ID_TEXT_LINE3),
	CAVE_CONST(SURFACE_ID_TEXT_LINE4),
	CAVE_CONST(SURFACE_ID_TEXT_LINE5),
	CAVE_CONST(SURFACE_ID_CREDIT_CAST),
	CAVE_CONST(SURFACE_ID_CREDITS_IMAGE),
	CAVE_CONST(SURFACE_ID_CASTS),

	// Misc
	CAVE_CONST(TSC_BUFFER_SIZE),
	CAVE_CONST(WINDOW_WIDTH),
	CAVE_CONST(WINDOW_HEIGHT),
	CAVE_CONST_NAMED("VS", 512),
};

static int ConstantsMetaIndex(lua_State* L)
{
	lua_pushnil(L);
	return 1;
}

static int ConstantsMetaNewIndex(lua_State* L)
{
	return luaL_error(L, "Cannot modify read-only Const table");
}

void PushConstantsTable(lua_State* L)
{
	lua_newtable(L);

	for (size_t i = 0; i < sizeof(ConstantTable) / sizeof(ConstantTable[0]); ++i)
	{
		const CONSTANT_TABLE* entry = &ConstantTable[i];

		int value = 0;

		switch (entry->type)
		{
			case CONST_STATIC:
				value = entry->static_value;
				break;

			default:
				continue;
		}

		lua_pushinteger(L, value);
		lua_setfield(L, -2, entry->name);
	}

	// Make table read-only
	lua_newtable(L);

	lua_pushcfunction(L, ConstantsMetaIndex);
	lua_setfield(L, -2, "__index");

	lua_pushcfunction(L, ConstantsMetaNewIndex);
	lua_setfield(L, -2, "__newindex");

	lua_setmetatable(L, -2);

	lua_setfield(L, -2, "Const");
}